/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteersRouteImport } from './routes/volunteers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MobileUploadRouteImport } from './routes/mobile-upload'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DeceasedRouteImport } from './routes/deceased'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as ChantingRouteImport } from './routes/chanting'
import { Route as ApprovalRouteImport } from './routes/approval'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteersLotusIdRouteImport } from './routes/volunteers.$lotusId'
import { Route as CheckinStrangersRouteImport } from './routes/checkin.strangers'
import { Route as CheckinRecordsRouteImport } from './routes/checkin.records'
import { Route as CheckinDetailsRouteImport } from './routes/checkin.details'
import { Route as VolunteersLotusIdEditRouteImport } from './routes/volunteers.$lotusId.edit'

const VolunteersRoute = VolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileUploadRoute = MobileUploadRouteImport.update({
  id: '/mobile-upload',
  path: '/mobile-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DeceasedRoute = DeceasedRouteImport.update({
  id: '/deceased',
  path: '/deceased',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChantingRoute = ChantingRouteImport.update({
  id: '/chanting',
  path: '/chanting',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalRoute = ApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteersLotusIdRoute = VolunteersLotusIdRouteImport.update({
  id: '/$lotusId',
  path: '/$lotusId',
  getParentRoute: () => VolunteersRoute,
} as any)
const CheckinStrangersRoute = CheckinStrangersRouteImport.update({
  id: '/strangers',
  path: '/strangers',
  getParentRoute: () => CheckinRoute,
} as any)
const CheckinRecordsRoute = CheckinRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => CheckinRoute,
} as any)
const CheckinDetailsRoute = CheckinDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => CheckinRoute,
} as any)
const VolunteersLotusIdEditRoute = VolunteersLotusIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => VolunteersLotusIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approval': typeof ApprovalRoute
  '/chanting': typeof ChantingRoute
  '/checkin': typeof CheckinRouteWithChildren
  '/deceased': typeof DeceasedRoute
  '/devices': typeof DevicesRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/mobile-upload': typeof MobileUploadRoute
  '/settings': typeof SettingsRoute
  '/volunteers': typeof VolunteersRouteWithChildren
  '/checkin/details': typeof CheckinDetailsRoute
  '/checkin/records': typeof CheckinRecordsRoute
  '/checkin/strangers': typeof CheckinStrangersRoute
  '/volunteers/$lotusId': typeof VolunteersLotusIdRouteWithChildren
  '/volunteers/$lotusId/edit': typeof VolunteersLotusIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approval': typeof ApprovalRoute
  '/chanting': typeof ChantingRoute
  '/checkin': typeof CheckinRouteWithChildren
  '/deceased': typeof DeceasedRoute
  '/devices': typeof DevicesRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/mobile-upload': typeof MobileUploadRoute
  '/settings': typeof SettingsRoute
  '/volunteers': typeof VolunteersRouteWithChildren
  '/checkin/details': typeof CheckinDetailsRoute
  '/checkin/records': typeof CheckinRecordsRoute
  '/checkin/strangers': typeof CheckinStrangersRoute
  '/volunteers/$lotusId': typeof VolunteersLotusIdRouteWithChildren
  '/volunteers/$lotusId/edit': typeof VolunteersLotusIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approval': typeof ApprovalRoute
  '/chanting': typeof ChantingRoute
  '/checkin': typeof CheckinRouteWithChildren
  '/deceased': typeof DeceasedRoute
  '/devices': typeof DevicesRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/mobile-upload': typeof MobileUploadRoute
  '/settings': typeof SettingsRoute
  '/volunteers': typeof VolunteersRouteWithChildren
  '/checkin/details': typeof CheckinDetailsRoute
  '/checkin/records': typeof CheckinRecordsRoute
  '/checkin/strangers': typeof CheckinStrangersRoute
  '/volunteers/$lotusId': typeof VolunteersLotusIdRouteWithChildren
  '/volunteers/$lotusId/edit': typeof VolunteersLotusIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approval'
    | '/chanting'
    | '/checkin'
    | '/deceased'
    | '/devices'
    | '/documents'
    | '/login'
    | '/mobile-upload'
    | '/settings'
    | '/volunteers'
    | '/checkin/details'
    | '/checkin/records'
    | '/checkin/strangers'
    | '/volunteers/$lotusId'
    | '/volunteers/$lotusId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/approval'
    | '/chanting'
    | '/checkin'
    | '/deceased'
    | '/devices'
    | '/documents'
    | '/login'
    | '/mobile-upload'
    | '/settings'
    | '/volunteers'
    | '/checkin/details'
    | '/checkin/records'
    | '/checkin/strangers'
    | '/volunteers/$lotusId'
    | '/volunteers/$lotusId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approval'
    | '/chanting'
    | '/checkin'
    | '/deceased'
    | '/devices'
    | '/documents'
    | '/login'
    | '/mobile-upload'
    | '/settings'
    | '/volunteers'
    | '/checkin/details'
    | '/checkin/records'
    | '/checkin/strangers'
    | '/volunteers/$lotusId'
    | '/volunteers/$lotusId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApprovalRoute: typeof ApprovalRoute
  ChantingRoute: typeof ChantingRoute
  CheckinRoute: typeof CheckinRouteWithChildren
  DeceasedRoute: typeof DeceasedRoute
  DevicesRoute: typeof DevicesRoute
  DocumentsRoute: typeof DocumentsRoute
  LoginRoute: typeof LoginRoute
  MobileUploadRoute: typeof MobileUploadRoute
  SettingsRoute: typeof SettingsRoute
  VolunteersRoute: typeof VolunteersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteers': {
      id: '/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof VolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-upload': {
      id: '/mobile-upload'
      path: '/mobile-upload'
      fullPath: '/mobile-upload'
      preLoaderRoute: typeof MobileUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deceased': {
      id: '/deceased'
      path: '/deceased'
      fullPath: '/deceased'
      preLoaderRoute: typeof DeceasedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chanting': {
      id: '/chanting'
      path: '/chanting'
      fullPath: '/chanting'
      preLoaderRoute: typeof ChantingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval': {
      id: '/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof ApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteers/$lotusId': {
      id: '/volunteers/$lotusId'
      path: '/$lotusId'
      fullPath: '/volunteers/$lotusId'
      preLoaderRoute: typeof VolunteersLotusIdRouteImport
      parentRoute: typeof VolunteersRoute
    }
    '/checkin/strangers': {
      id: '/checkin/strangers'
      path: '/strangers'
      fullPath: '/checkin/strangers'
      preLoaderRoute: typeof CheckinStrangersRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/checkin/records': {
      id: '/checkin/records'
      path: '/records'
      fullPath: '/checkin/records'
      preLoaderRoute: typeof CheckinRecordsRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/checkin/details': {
      id: '/checkin/details'
      path: '/details'
      fullPath: '/checkin/details'
      preLoaderRoute: typeof CheckinDetailsRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/volunteers/$lotusId/edit': {
      id: '/volunteers/$lotusId/edit'
      path: '/edit'
      fullPath: '/volunteers/$lotusId/edit'
      preLoaderRoute: typeof VolunteersLotusIdEditRouteImport
      parentRoute: typeof VolunteersLotusIdRoute
    }
  }
}

interface CheckinRouteChildren {
  CheckinDetailsRoute: typeof CheckinDetailsRoute
  CheckinRecordsRoute: typeof CheckinRecordsRoute
  CheckinStrangersRoute: typeof CheckinStrangersRoute
}

const CheckinRouteChildren: CheckinRouteChildren = {
  CheckinDetailsRoute: CheckinDetailsRoute,
  CheckinRecordsRoute: CheckinRecordsRoute,
  CheckinStrangersRoute: CheckinStrangersRoute,
}

const CheckinRouteWithChildren =
  CheckinRoute._addFileChildren(CheckinRouteChildren)

interface VolunteersLotusIdRouteChildren {
  VolunteersLotusIdEditRoute: typeof VolunteersLotusIdEditRoute
}

const VolunteersLotusIdRouteChildren: VolunteersLotusIdRouteChildren = {
  VolunteersLotusIdEditRoute: VolunteersLotusIdEditRoute,
}

const VolunteersLotusIdRouteWithChildren =
  VolunteersLotusIdRoute._addFileChildren(VolunteersLotusIdRouteChildren)

interface VolunteersRouteChildren {
  VolunteersLotusIdRoute: typeof VolunteersLotusIdRouteWithChildren
}

const VolunteersRouteChildren: VolunteersRouteChildren = {
  VolunteersLotusIdRoute: VolunteersLotusIdRouteWithChildren,
}

const VolunteersRouteWithChildren = VolunteersRoute._addFileChildren(
  VolunteersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApprovalRoute: ApprovalRoute,
  ChantingRoute: ChantingRoute,
  CheckinRoute: CheckinRouteWithChildren,
  DeceasedRoute: DeceasedRoute,
  DevicesRoute: DevicesRoute,
  DocumentsRoute: DocumentsRoute,
  LoginRoute: LoginRoute,
  MobileUploadRoute: MobileUploadRoute,
  SettingsRoute: SettingsRoute,
  VolunteersRoute: VolunteersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
